const gamesList = [
  '1v1.LOL',
  '7 Days to Die',
  'Aim Gods',
  'Aim Lab',
  'Aiming.Pro',
  'Aimtastic',
  'Apex Legends',
  'Arma 3',
  'Battalion 1944',
  'Battlefield V/1/Hardline',
  'Black Squad',
  'Bloodhunt',
  'Borderlands 1/2',
  'Borderlands 3',
  'Call of Duty: Black Ops 4',
  'Call of Duty: Black Ops Cold War',
  'Call of Duty: Modern Warfare',
  'Call of Duty: Warzone',
  'Call of Duty: WWII',
  'Creative Destruction',
  'CS 1.6',
  'CS:GO',
  'Cyberpunk 2077',
  'Darwin Project',
  'DayZ',
  'Deep Rock Galactic',
  'Destiny 2',
  'Doom Eternal',
  'Dying Light',
  'Escape from Tarkov',
  'Fallout 4',
  'Far Cry 3',
  'Far Cry 4',
  'Far Cry 5',
  'Far Cry Primal',
  'Fortnite',
  "Garry's Mod",
  'Gears 5',
  'Halo',
  'Halo Infinite',
  'Heroes & Generals',
  'Hunt: Showdown',
  'Hyperscape',
  'Insurgency',
  'Insurgency: Sandstorm',
  'Ironsight',
  'Krunker',
  'Line of Sight',
  'Minecraft Java Edition',
  'Overwatch',
  'Overwatch 2',
  'Paladins',
  'Payday 2',
  'PUBG',
  'Quake Live',
  'Realm Royale',
  'Ring of Elysium',
  'Roblox',
  'Rogue Company',
  'Rust',
  'Splitgate',
  'Squad',
  'Team Fortress 2',
  'Titanfall 2',
  "Tom Clancy's Rainbow 6: Siege",
  "Tom Clancy's The Division 2",
  'Unturned',
  'Valheim',
  'Valorant',
  'Warface',
  'Warframe',
  'Zula',
];
